---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- GBD:
    - ADH.com:
        - abbr: AD
          href: https://www.adh.com/

- Marketing:
    - Github:
        - abbr: GH
          href: https://github.com/

- Social:
    - Reddit:
        - abbr: RE
          href: https://reddit.com/

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/

          