---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

#- resources:
#    cpu: true
#    memory: true
#    disk: /

- datetime:
    text_size: md
    format:
        dateStyle: long
        timeStyle: short
        hour12: false

- search:
    provider: google # google, duckduckgo, bing, baidu, brave or custom
    focus: false # Optional, will set focus to the search bar on page load
    showSearchSuggestions: true # Optional, will show search suggestions. Defaults to false
    target: _self # One of _self, _blank, _parent or _top
 